version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: --authentication_policy=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hobisabi
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data:
